apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-dist-logging.yaml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-dist-logging.yaml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: fluentd
    spec:
      containers:
        - image: fluentd
          name: fluentd
          imagePullPolicy: Never
          ## command: ["/bin/sh"]
          ## args: ["-c", "mkdir -p /buffer && gem install fluent-plugin-kafka --no-doc --version 0.7.9 && /fluentd/entrypoint.sh"]
          ports:
            - containerPort: 24224
            - containerPort: 24224
              protocol: UDP
          resources: {}
          # volumeMounts:
          #   - mountPath: /fluentd/etc1
          #     name: fluentd-claim0
      restartPolicy: Always
      volumes:
        - name: fluentd-claim0
          persistentVolumeClaim:
            claimName: fluentd-claim0
status: {}
