version: "3.3"
services:
  backend:
    container_name: backend
    build:
      context: .
    # volumes:
    #   - ./:/usr/src/backend
    command: ./a.sh
    ports:
      - "3001:3001"
    networks:
      - net
networks:
  net:
    driver: bridge