apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-dist-logging.yaml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: gumball
  name: gumball
spec:
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: gumball
status:
  loadBalancer: {}
